name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Check code syntax
      #   run: |
      #     pip install pylint flake8
      #     pylint app tests
      #     flake8 app tests

      # - name: Run tests and generate coverage
      #   run: |
      #     pip install pytest pytest-cov
      #     pytest

      - name: Generate coverage report
        run: |
          pip install coverage
          coverage report -m
